# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build pytest ruff
        pip install -r requirements.txt

    - name: Code style
      run: |
        pre-commit run --all-files

    - name: Pytest
      run: |
        PYTHONPATH=src pytest

    - name: Build & Install test
      run: |
        python -m build
        pip install dist/pycountries-*.tar.gz
